name: Adam Žúrek, Student of Slovak University of Technology
markdown: kramdown
permalink: /projects/:title
plugins:
  - jekyll-timeago
collections:
  wp:
    output: true
    permalink: /:collection/:title